summary: Update the gce test bucket

systems: [ubuntu-20.04-64]

kill-timeout: 30m

restore: |
    rm -rf snapd spread-amd64.tar.gz spread
   
execute: |
    apt install -y xdelta3
    wget https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64.tar.gz
    tar -xvzf spread-amd64.tar.gz

    mkdir -p ~/.config/gcloud
    mv sa_user.json ~/.config/gcloud/application_default_credentials.json

    git clone https://github.com/canonical/snapd.git
    mv sa_baker.json snapd/sa.json

    ( cd snapd && ../spread google:tests/nightly/upload-snapd-to-gce )
